services:
  # N8N Service
  - type: web
    name: n8n-automation
    runtime: docker
    dockerContext: ./n8n
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        sync: false
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: neondb
      - key: DB_POSTGRESDB_USER
        sync: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
    plan: free

  # Moltbot Service
  - type: web
    name: moltbot-agent
    runtime: docker
    dockerContext: ./moltbot
    # Si Moltbot usa variables, agregarlas aca (ej API Keys)
    envVars:
      - key: PORT
        value: 8000
    plan: free
